### ISSUE TITLE
Please Opensource the program

### ISSUE THREAD

**Issue by debendraoli** [gt0day/Burp-Suite#3]
I am little skeptical to use this jar file.

Open sourcing the program would clear my doubts.

**Comment by gt0day** [comment]
https://www.virustotal.com/gui/file/dcdf28acf360554a5a98d78f403c96ccea500be24b27d02b020e142820637c0a

**Comment by NasvekL** [comment]
> I am little skeptical to use this jar file.
> 
> Open sourcing the program would clear my doubts.

Its just a keygen. I decoompiled the jar and its just a keygen.
